import test from "./Assets/freshmart.png"
export const products = {
  Fruits: [
    {
      id: "F-01",
      name: "Apple",
      category: "Fruits",
      price: 50,
      discount: 0,
      image: test,
      weight: 1,
      description:
        "Fresh and juicy apples, perfect for a healthy snack. Rich in vitamins and antioxidants.",
    },
    {
      id: "F-02",
      name: "Banana",
      category: "Fruits",
      price: 20,
      discount: 5,
      image: test,
      weight: 1,
      description:
        "Ripe bananas, a great source of potassium and energy. Ideal for breakfast or a quick snack.",
    },
    {
      id: "F-03",
      name: "Orange",
      category: "Fruits",
      price: 40,
      discount: 10,
      image: "",
      weight: 1,
      description:
        "Sweet and tangy oranges, full of vitamin C. Great for juicing or eating fresh.",
    },
    {
      id: "F-04",
      name: "Grapes",
      category: "Fruits",
      price: 60,
      discount: 10,
      image: "",
      weight: 1,
      description:
        "Seedless grapes, perfect for snacking or adding to salads. Rich in antioxidants.",
    },
    {
      id: "F-05",
      name: "Pineapple",
      category: "Fruits",
      price: 70,
      discount: 20,
      image: "",
      weight: 1,
      description:
        "Tropical pineapples, sweet and juicy. Great for smoothies, desserts, or eating fresh.",
    },
    {
      id: "F-06",
      name: "Mango",
      category: "Fruits",
      price: 80,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Delicious mangoes, full of flavor and nutrients. Perfect for desserts, smoothies, or eating fresh.",
    },
    {
      id: "F-07",
      name: "Strawberry",
      category: "Fruits",
      price: 90,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh strawberries, sweet and juicy. Great for desserts, salads, or eating fresh.",
    },
    {
      id: "F-08",
      name: "Blueberry",
      category: "Fruits",
      price: 100,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Blueberries, rich in antioxidants and vitamins. Perfect for smoothies, desserts, or snacking.",
    },
    {
      id: "F-09",
      name: "Papaya",
      category: "Fruits",
      price: 55,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Sweet and tropical papayas. Great for digestion and packed with nutrients.",
    },
    {
      id: "F-10",
      name: "Watermelon",
      category: "Fruits",
      price: 45,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Refreshing watermelons, perfect for hot days. Full of hydration and nutrients.",
    },
    {
      id: "F-11",
      name: "Peach",
      category: "Fruits",
      price: 60,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy peaches, sweet and flavorful. Great for desserts, snacks, or eating fresh.",
    },
    {
      id: "F-12",
      name: "Plum",
      category: "Fruits",
      price: 50,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Ripe plums, perfect for snacking or adding to dishes. Rich in vitamins and fiber.",
    },
    {
      id: "F-13",
      name: "Kiwi",
      category: "Fruits",
      price: 70,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tangy kiwis, full of vitamin C and fiber. Great for salads, smoothies, or eating fresh.",
    },
    {
      id: "F-14",
      name: "Pomegranate",
      category: "Fruits",
      price: 90,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy pomegranates, rich in antioxidants. Perfect for juicing or adding to dishes.",
    },
    {
      id: "F-15",
      name: "Guava",
      category: "Fruits",
      price: 35,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Sweet and aromatic guavas. Great for digestion and packed with vitamins.",
    },
    {
      id: "F-16",
      name: "Lychee",
      category: "Fruits",
      price: 80,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Exotic lychees, sweet and juicy. Perfect for desserts or eating fresh.",
    },
    {
      id: "F-17",
      name: "Pear",
      category: "Fruits",
      price: 50,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Crunchy pears, sweet and flavorful. Great for snacking or adding to salads.",
    },
    {
      id: "F-18",
      name: "Cherry",
      category: "Fruits",
      price: 120,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy cherries, perfect for desserts or eating fresh. Rich in antioxidants.",
    },
    {
      id: "F-19",
      name: "Blackberry",
      category: "Fruits",
      price: 110,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Blackberries, rich in vitamins and antioxidants. Perfect for smoothies, desserts, or snacking.",
    },
    {
      id: "F-20",
      name: "Coconut",
      category: "Fruits",
      price: 30,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh coconuts, full of nutrients and hydration. Great for drinking or cooking.",
    },
  ],
  Vegetables: [
    {
      id: "V-01",
      name: "Tomato",
      category: "Vegetables",
      price: 30,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Ripe tomatoes, perfect for salads, cooking, or making sauces. Rich in vitamins and antioxidants.",
    },
    {
      id: "V-02",
      name: "Potato",
      category: "Vegetables",
      price: 20,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Versatile potatoes, great for boiling, baking, or frying. A staple in many cuisines.",
    },
    {
      id: "V-03",
      name: "Carrot",
      category: "Vegetables",
      price: 40,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Crunchy carrots, perfect for salads, cooking, or snacking. Rich in beta-carotene and fiber.",
    },
    {
      id: "V-04",
      name: "Onion",
      category: "Vegetables",
      price: 25,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Flavorful onions, essential for cooking. Great for adding depth to dishes and rich in antioxidants.",
    },
    {
      id: "V-05",
      name: "Broccoli",
      category: "Vegetables",
      price: 50,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh broccoli, perfect for steaming, stir-frying, or eating raw. Packed with vitamins and fiber.",
    },
    {
      id: "V-06",
      name: "Cauliflower",
      category: "Vegetables",
      price: 45,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Versatile cauliflower, great for roasting, mashing, or adding to dishes. Rich in vitamins and fiber.",
    },
    {
      id: "V-07",
      name: "Spinach",
      category: "Vegetables",
      price: 35,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh spinach, perfect for salads, cooking, or smoothies. Packed with iron and vitamins.",
    },
    {
      id: "V-08",
      name: "Capsicum",
      category: "Vegetables",
      price: 55,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Colorful capsicums, great for stir-frying, salads, or roasting. Rich in vitamins and antioxidants.",
    },
    {
      id: "V-09",
      name: "Cucumber",
      category: "Vegetables",
      price: 25,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh cucumbers, perfect for salads, sandwiches, or eating raw. Hydrating and low in calories.",
    },
    {
      id: "V-10",
      name: "Lettuce",
      category: "Vegetables",
      price: 60,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Crisp lettuce, perfect for salads, sandwiches, or wraps. Refreshing and low in calories.",
    },
    {
      id: "V-11",
      name: "Zucchini",
      category: "Vegetables",
      price: 45,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh zucchini, great for grilling, stir-frying, or adding to dishes. Low in calories and rich in vitamins.",
    },
    {
      id: "V-12",
      name: "Eggplant",
      category: "Vegetables",
      price: 40,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Versatile eggplants, perfect for roasting, grilling, or adding to dishes. Rich in fiber and antioxidants.",
    },
    {
      id: "V-13",
      name: "Bell Pepper",
      category: "Vegetables",
      price: 50,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Colorful bell peppers, great for salads, stir-fries, or roasting. Packed with vitamins and antioxidants.",
    },
    {
      id: "V-14",
      name: "Sweet Potato",
      category: "Vegetables",
      price: 30,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Nutritious sweet potatoes, perfect for baking, roasting, or mashing. Rich in vitamins and fiber.",
    },
    {
      id: "V-15",
      name: "Green Beans",
      category: "Vegetables",
      price: 35,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh green beans, great for steaming, stir-frying, or adding to dishes. Rich in vitamins and fiber.",
    },
    {
      id: "V-16",
      name: "Peas",
      category: "Vegetables",
      price: 30,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Sweet peas, perfect for adding to dishes, salads, or eating fresh. Packed with protein and vitamins.",
    },
    {
      id: "V-17",
      name: "Radish",
      category: "Vegetables",
      price: 20,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Crisp radishes, perfect for salads, sandwiches, or snacking. Low in calories and high in vitamins.",
    },
    {
      id: "V-18",
      name: "Celery",
      category: "Vegetables",
      price: 25,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh celery, great for salads, cooking, or snacking. Low in calories and high in fiber.",
    },
    {
      id: "V-19",
      name: "Kale",
      category: "Vegetables",
      price: 55,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Nutritious kale, perfect for salads, smoothies, or cooking. Packed with vitamins and antioxidants.",
    },
    {
      id: "V-20",
      name: "Beetroot",
      category: "Vegetables",
      price: 40,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh beetroot, great for salads, cooking, or juicing. Rich in vitamins and minerals.",
    },
  ],
  Meat: [
    {
      id: "M-01",
      name: "Chicken Breast",
      category: "Meat",
      price: 150,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Lean and tender chicken breast, perfect for grilling, baking, or adding to dishes. High in protein.",
    },
    {
      id: "M-02",
      name: "Chicken Thigh",
      category: "Meat",
      price: 140,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy chicken thighs, great for grilling, roasting, or adding to dishes. Flavorful and high in protein.",
    },
    {
      id: "M-03",
      name: "Beef Steak",
      category: "Meat",
      price: 250,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender beef steak, perfect for grilling, pan-frying, or broiling. High in protein and rich in flavor.",
    },
    {
      id: "M-04",
      name: "Pork Chops",
      category: "Meat",
      price: 220,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy pork chops, great for grilling, baking, or pan-frying. Rich in protein and flavor.",
    },
    {
      id: "M-05",
      name: "Lamb Chops",
      category: "Meat",
      price: 270,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender lamb chops, perfect for grilling, roasting, or pan-frying. High in protein and rich in flavor.",
    },
    {
      id: "M-06",
      name: "Turkey Breast",
      category: "Meat",
      price: 200,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Lean and tender turkey breast, great for roasting, grilling, or adding to dishes. High in protein.",
    },
    {
      id: "M-07",
      name: "Salmon Fillet",
      category: "Meat",
      price: 300,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh salmon fillet, perfect for grilling, baking, or pan-frying. Rich in omega-3 fatty acids and protein.",
    },
    {
      id: "M-08",
      name: "Shrimp",
      category: "Meat",
      price: 180,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy shrimp, great for grilling, frying, or adding to dishes. High in protein and low in fat.",
    },
    {
      id: "M-09",
      name: "Duck Breast",
      category: "Meat",
      price: 260,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender duck breast, perfect for grilling, roasting, or pan-frying. Rich in flavor and high in protein.",
    },
    {
      id: "M-10",
      name: "Bacon",
      category: "Meat",
      price: 230,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Crispy bacon, perfect for breakfast, sandwiches, or adding to dishes. Rich in flavor and protein.",
    },
    {
      id: "M-11",
      name: "Ground Beef",
      category: "Meat",
      price: 200,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Versatile ground beef, perfect for burgers, meatballs, or adding to dishes. High in protein and flavor.",
    },
    {
      id: "M-12",
      name: "Ham",
      category: "Meat",
      price: 210,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Savory ham, great for sandwiches, salads, or adding to dishes. Rich in protein and flavor.",
    },
    {
      id: "M-13",
      name: "Lamb Shank",
      category: "Meat",
      price: 280,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender lamb shank, perfect for slow cooking, braising, or roasting. Rich in flavor and high in protein.",
    },
    {
      id: "M-14",
      name: "Veal Cutlets",
      category: "Meat",
      price: 290,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender veal cutlets, great for grilling, pan-frying, or adding to dishes. High in protein and flavor.",
    },
    {
      id: "M-15",
      name: "Pork Sausage",
      category: "Meat",
      price: 190,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Savory pork sausage, perfect for breakfast, grilling, or adding to dishes. Rich in flavor and protein.",
    },
    {
      id: "M-16",
      name: "Chicken Wings",
      category: "Meat",
      price: 160,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy chicken wings, great for grilling, frying, or baking. High in protein and flavor.",
    },
    {
      id: "M-17",
      name: "Beef Ribs",
      category: "Meat",
      price: 240,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tender beef ribs, perfect for grilling, roasting, or slow cooking. Rich in flavor and protein.",
    },
    {
      id: "M-18",
      name: "Prawns",
      category: "Meat",
      price: 210,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh prawns, great for grilling, frying, or adding to dishes. High in protein and low in fat.",
    },
    {
      id: "M-19",
      name: "Turkey Legs",
      category: "Meat",
      price: 220,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Juicy turkey legs, perfect for roasting, grilling, or slow cooking. High in protein and flavor.",
    },
    {
      id: "M-20",
      name: "Salami",
      category: "Meat",
      price: 230,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Savory salami, great for sandwiches, pizzas, or adding to dishes. Rich in flavor and protein.",
    },
  ],
  Dairy: [
    {
      id: "D-01",
      name: "Milk",
      category: "Dairy",
      price: 40,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh milk, perfect for drinking, cooking, or adding to beverages. High in calcium and vitamins.",
    },
    {
      id: "D-02",
      name: "Cheese",
      category: "Dairy",
      price: 100,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Rich and creamy cheese, great for sandwiches, cooking, or snacking. High in calcium and protein.",
    },
    {
      id: "D-03",
      name: "Butter",
      category: "Dairy",
      price: 80,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Creamy butter, perfect for cooking, baking, or spreading. Rich in flavor and vitamins.",
    },
    {
      id: "D-04",
      name: "Yogurt",
      category: "Dairy",
      price: 60,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Smooth and creamy yogurt, great for eating, cooking, or adding to dishes. Rich in probiotics and vitamins.",
    },
    {
      id: "D-05",
      name: "Cream",
      category: "Dairy",
      price: 70,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Rich and smooth cream, perfect for cooking, baking, or adding to dishes. High in fat and flavor.",
    },
    {
      id: "D-06",
      name: "Cottage Cheese",
      category: "Dairy",
      price: 90,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh cottage cheese, great for salads, cooking, or snacking. High in protein and calcium.",
    },
    {
      id: "D-07",
      name: "Ice Cream",
      category: "Dairy",
      price: 110,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Delicious ice cream, perfect for desserts, snacks, or treats. Rich in flavor and creamy texture.",
    },
    {
      id: "D-08",
      name: "Ghee",
      category: "Dairy",
      price: 120,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Pure ghee, perfect for cooking, baking, or adding to dishes. Rich in flavor and vitamins.",
    },
    {
      id: "D-09",
      name: "Buttermilk",
      category: "Dairy",
      price: 50,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Refreshing buttermilk, great for drinking, cooking, or adding to dishes. Low in fat and high in vitamins.",
    },
    {
      id: "D-10",
      name: "Paneer",
      category: "Dairy",
      price: 130,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fresh paneer, perfect for cooking, grilling, or adding to dishes. High in protein and calcium.",
    },
    {
      id: "D-11",
      name: "Ricotta",
      category: "Dairy",
      price: 90,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Creamy ricotta cheese, great for baking, cooking, or adding to dishes. Rich in protein and calcium.",
    },
    {
      id: "D-12",
      name: "Sour Cream",
      category: "Dairy",
      price: 70,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tangy sour cream, perfect for cooking, baking, or adding to dishes. Rich in flavor and creamy texture.",
    },
    {
      id: "D-13",
      name: "Whipping Cream",
      category: "Dairy",
      price: 80,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Rich whipping cream, great for desserts, cooking, or adding to dishes. High in fat and creamy texture.",
    },
    {
      id: "D-14",
      name: "Mozzarella",
      category: "Dairy",
      price: 100,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Soft and stretchy mozzarella cheese, perfect for pizzas, sandwiches, or salads. Rich in calcium and protein.",
    },
    {
      id: "D-15",
      name: "Parmesan",
      category: "Dairy",
      price: 110,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Aged parmesan cheese, great for grating, cooking, or adding to dishes. Rich in flavor and protein.",
    },
    {
      id: "D-16",
      name: "Feta",
      category: "Dairy",
      price: 95,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Tangy feta cheese, perfect for salads, cooking, or snacking. High in protein and calcium.",
    },
    {
      id: "D-17",
      name: "Blue Cheese",
      category: "Dairy",
      price: 115,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Bold and tangy blue cheese, great for salads, cooking, or adding to dishes. Rich in flavor and protein.",
    },
    {
      id: "D-18",
      name: "Swiss Cheese",
      category: "Dairy",
      price: 105,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Nutty and mild Swiss cheese, perfect for sandwiches, cooking, or snacking. High in calcium and protein.",
    },
    {
      id: "D-19",
      name: "Goat Cheese",
      category: "Dairy",
      price: 120,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Creamy goat cheese, ideal for salads, cooking, or spreading. Rich in flavor and nutrients.",
    },
    {
      id: "D-20",
      name: "Provolone",
      category: "Dairy",
      price: 110,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Mild and tangy provolone cheese, perfect for sandwiches, cooking, or adding to dishes. High in calcium and protein.",
    },
  ],
  Spices: [
    {
      id: "S-01",
      name: "Turmeric",
      category: "Spices",
      price: 500,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Turmeric, known for its vibrant color and anti-inflammatory properties, is a staple in many cuisines. It's often used in curries, soups, and sauces.",
    },
    {
      id: "S-02",
      name: "Cumin",
      category: "Spices",
      price: 450,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Cumin seeds, with their earthy flavor, are essential in spice blends like garam masala and are used in a variety of dishes from Indian to Mexican cuisine.",
    },
    {
      id: "S-03",
      name: "Coriander",
      category: "Spices",
      price: 400,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Coriander seeds, with their citrusy and slightly sweet flavor, are used in both sweet and savory dishes, including curries, soups, and marinades.",
    },
    {
      id: "S-04",
      name: "Black Pepper",
      category: "Spices",
      price: 600,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Black peppercorns, known for their pungent heat, are a universal seasoning that enhances the flavor of any dish, from meats to vegetables.",
    },
    {
      id: "S-05",
      name: "Cardamom",
      category: "Spices",
      price: 1500,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Cardamom pods, with their aromatic and slightly sweet flavor, are used in both savory and sweet dishes, including curries, rice, and desserts.",
    },
    {
      id: "S-06",
      name: "Cinnamon",
      category: "Spices",
      price: 800,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Cinnamon sticks, known for their warm and sweet flavor, are used in both savory and sweet dishes, from curries to baked goods.",
    },
    {
      id: "S-07",
      name: "Cloves",
      category: "Spices",
      price: 1200,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Cloves, with their intense aroma and flavor, are used sparingly in dishes like biryanis, stews, and desserts for their distinctive taste.",
    },
    {
      id: "S-08",
      name: "Nutmeg",
      category: "Spices",
      price: 10000,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Nutmeg, with its warm, nutty flavor, is used in both sweet and savory dishes, including desserts, sauces, and spice blends.",
    },
    {
      id: "S-09",
      name: "Paprika",
      category: "Spices",
      price: 550,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Paprika, made from ground red peppers, adds a mild, sweet flavor and vibrant color to a variety of dishes, including soups, stews, and meats.",
    },
    {
      id: "S-10",
      name: "Chili Powder",
      category: "Spices",
      price: 500,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Chili powder, a blend of ground chilies and other spices, adds heat and flavor to dishes like chili con carne, tacos, and stews.",
    },
    {
      id: "S-11",
      name: "Ginger Powder",
      category: "Spices",
      price: 700,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Ground ginger, with its warm and spicy flavor, is used in both sweet and savory dishes, including cookies, curries, and marinades.",
    },
    {
      id: "S-12",
      name: "Garlic Powder",
      category: "Spices",
      price: 650,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Garlic powder, with its strong and pungent flavor, is a versatile spice used in a variety of dishes, from sauces to seasoning blends.",
    },
    {
      id: "S-13",
      name: "Fennel Seeds",
      category: "Spices",
      price: 500,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fennel seeds, with their sweet and licorice-like flavor, are used in both sweet and savory dishes, including spice blends, teas, and baked goods.",
    },
    {
      id: "S-14",
      name: "Fenugreek Seeds",
      category: "Spices",
      price: 450,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Fenugreek seeds, with their slightly bitter and nutty flavor, are often used in spice blends and pickles, and have various health benefits.",
    },
    {
      id: "S-15",
      name: "Mustard Seeds",
      category: "Spices",
      price: 550,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Mustard seeds, with their pungent and spicy flavor, are used in pickling, spice blends, and condiments like mustard sauce.",
    },
    {
      id: "S-16",
      name: "Bay Leaves",
      category: "Spices",
      price: 3000,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Bay leaves, with their subtle and aromatic flavor, are used to enhance the taste of soups, stews, and sauces. They are usually removed before serving.",
    },
    {
      id: "S-17",
      name: "Saffron",
      category: "Spices",
      price: 50000,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Saffron, known for its distinct flavor and vibrant color, is used in various dishes, including paella, risotto, and desserts. It's one of the most expensive spices in the world.",
    },
    {
      id: "S-18",
      name: "Curry Powder",
      category: "Spices",
      price: 600,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Curry powder, a blend of spices including turmeric, coriander, and cumin, adds a warm and complex flavor to curries, soups, and stews.",
    },
    {
      id: "S-19",
      name: "Thyme",
      category: "Spices",
      price: 4000,
      discount: "",
      image: "",
      weight:1,
      description:
        "Dried thyme, with its earthy and slightly minty flavor, is used to season meats, vegetables, and soups, and is a staple in many spice blends.",
    },
    {
      id: "S-20",
      name: "Oregano",
      category: "Spices",
      price: 5000,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Dried oregano, with its robust and slightly bitter flavor, is commonly used in Italian, Greek, and Mexican cuisines, perfect for pizzas, pastas, and sauces.",
    },
  ],
  Oils: [
    {
      id: "O-01",
      name: "Olive Oil",
      category: "Oils",
      price: 250,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Extra virgin olive oil, known for its rich flavor and health benefits, is perfect for salads, cooking, and drizzling over dishes.",
    },
    {
      id: "O-02",
      name: "Canola Oil",
      category: "Oils",
      price: 200,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Canola oil, with its mild flavor and high smoke point, is ideal for frying, baking, and everyday cooking.",
    },
    {
      id: "O-03",
      name: "Coconut Oil",
      category: "Oils",
      price: 300,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Virgin coconut oil, known for its distinct flavor and health benefits, is perfect for cooking, baking, and skin care.",
    },
    {
      id: "O-04",
      name: "Sunflower Oil",
      category: "Oils",
      price: 180,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Sunflower oil, with its light flavor and high smoke point, is great for frying, baking, and sautéing.",
    },
    {
      id: "O-05",
      name: "Sesame Oil",
      category: "Oils",
      price: 220,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Sesame oil, with its nutty flavor and aroma, is perfect for Asian cuisine, dressings, and marinades.",
    },
    {
      id: "O-06",
      name: "Avocado Oil",
      category: "Oils",
      price: 350,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Avocado oil, rich in healthy fats, is ideal for high-heat cooking, dressings, and drizzling over dishes.",
    },
    {
      id: "O-07",
      name: "Grapeseed Oil",
      category: "Oils",
      price: 240,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Grapeseed oil, known for its neutral flavor and high smoke point, is perfect for frying, baking, and salad dressings.",
    },
    {
      id: "O-08",
      name: "Peanut Oil",
      category: "Oils",
      price: 230,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Peanut oil, with its mild flavor and high smoke point, is ideal for frying, sautéing, and Asian cuisine.",
    },
    {
      id: "O-09",
      name: "Corn Oil",
      category: "Oils",
      price: 190,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Corn oil, with its light flavor and versatility, is great for frying, baking, and everyday cooking.",
    },
    {
      id: "O-10",
      name: "Flaxseed Oil",
      category: "Oils",
      price: 400,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Flaxseed oil, rich in omega-3 fatty acids, is ideal for dressings, smoothies, and drizzling over dishes. Not suitable for high-heat cooking.",
    },
    {
      id: "O-11",
      name: "Walnut Oil",
      category: "Oils",
      price: 420,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Walnut oil, known for its rich, nutty flavor, is ideal for salad dressings, drizzling over dishes, and baking. High in omega-3 fatty acids.",
    },
    {
      id: "O-12",
      name: "Macadamia Oil",
      category: "Oils",
      price: 500,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Macadamia oil, with its buttery and slightly sweet flavor, is perfect for high-heat cooking, baking, and dressings. Rich in monounsaturated fats.",
    },
    {
      id: "O-13",
      name: "Hemp Oil",
      category: "Oils",
      price: 350,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Hemp oil, known for its nutty flavor and health benefits, is best used for dressings, dips, and drizzling. Not suitable for high-heat cooking.",
    },
    {
      id: "O-14",
      name: "Rice Bran Oil",
      category: "Oils",
      price: 200,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Rice bran oil, with its mild flavor and high smoke point, is ideal for frying, baking, and everyday cooking. Contains antioxidants and vitamins.",
    },
    {
      id: "O-15",
      name: "Almond Oil",
      category: "Oils",
      price: 450,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Almond oil, with its light and nutty flavor, is perfect for salad dressings, baking, and skin care. Rich in vitamins and healthy fats.",
    },
    {
      id: "O-16",
      name: "Soybean Oil",
      category: "Oils",
      price: 180,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Soybean oil, with its neutral flavor and high smoke point, is ideal for frying, baking, and sautéing. Commonly used in processed foods.",
    },
    {
      id: "O-17",
      name: "Pistachio Oil",
      category: "Oils",
      price: 470,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Pistachio oil, known for its unique and rich flavor, is perfect for dressings, baking, and drizzling over dishes. High in healthy fats and vitamins.",
    },
    {
      id: "O-18",
      name: "Pumpkin Seed Oil",
      category: "Oils",
      price: 380,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Pumpkin seed oil, with its deep, nutty flavor, is ideal for dressings, dips, and drizzling. Contains antioxidants and essential fatty acids.",
    },
    {
      id: "O-19",
      name: "Camelina Oil",
      category: "Oils",
      price: 400,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Camelina oil, known for its mild flavor and high omega-3 content, is perfect for salad dressings, cooking, and baking. High smoke point.",
    },
    {
      id: "O-20",
      name: "Black Seed Oil",
      category: "Oils",
      price: 450,
      discount: "",
      image: "",
      weight: 1,
      description:
        "Black seed oil, known for its strong, slightly bitter flavor and health benefits, is used in dressings, dips, and drizzling over dishes.",
    },
  ],
};



